# Modalità dell'applicazione:
# true = Demo Mode (dati salvati solo in memoria RAM, non persiste nulla)
# false = Full Mode (salva su database o filesystem)
app.mode.demo=true

# Se app.mode.demo=false, scegliamo il tipo di persistenza:
# db = Database (es. MySQL)
# fs = File System (es. file CSV)
app.persistence.type=fs